apiVersion: v1
kind: ReplicationController
metadata: 
  name: pay-rc
spec:
  replicas: 3
  selector:
    app: pay
  template:
    metadata: 
      labels:
        app: pay
    spec:
      containers:
        - name: marvel-pay
          image: smlinux/pay
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: pay-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: pay
