apiVersion: v1
kind: Pod
metadata:
  name: annotation-pod
  annotations:
    bulder: "jehyun"
    buildDate: "220905"
    imageRegistry: "https://hub.docker.com"
spec:
  containers:
  - image: nginx:1.14
    name: nginx-container
    ports:
    - containerPort: 80
