apiVersion: v1
kind: Pod
metadata:
  name: genid-volume-secret
spec:
  containers:
    - image: smlinux/genid:env
      name: fakeid-generator
      env:
        - name: INTERVAL
          valueFrom:
            secretKeyRef:
              name: tls-secret
              key: INTERVAL
      volumeMounts:
        - name: html
          mountPath: /webdata
    - image: nginx:1.14
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      ports: 
      - containerPort: 80
  volumes: 
    - name: html
      emptyDir: {}
    - name: config
      secret:
        secretName: tls-secret
        items:
          - key: nginx-config.conf
            path: nginx-config.conf
