apiVersion: v1
kind: Pod
metadata:
  name: genid-volume
spec:
  containers:
    - image: smlinux/genid:env
      name: fakeid
      envFrom:
        - configMapRef:
            name: test-config
      volumeMounts:
        - name: html
          mountPath: /webdata
    - image: nginx:1.14
      name: web-server
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
      ports: 
      - containerPort: 80
  volumes: 
    - name: html
      emptyDir: {}
    - name: config
      configMap:
        name: test-config
        items:
          - key: nginx-config.conf
            path: nginx-config.conf
