apiVersion: v1
kind: Pod
metadata:
  name: label-pod-demo2
  labels:
    name: loginui
    rel: stable
spec:
  containers:
  - image: nginx:1.14
    name: nginx-label
    ports:
    - containerPort: 80
