apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-over-resources
spec:
  containers:
    - image: nginx:1.14
      name: nginx-container
      ports: 
        - containerPort: 80
          protocol: TCP 
      resources:
        requests:
          cpu: 4
          memory: 250Mi
