apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod2
spec:
  containers:
  - image: nginx:1.14
    name: nginx-label
    ports:
    - containerPort: 80
  nodeSelector:
    gpu: "false"
    disk: ssd
