apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod
spec:
  containers:
  - image: nginx:1.14
    name: nginx-label
    ports:
    - containerPort: 80
  nodeSelector:
    gpu: "true"
    disk: ssd
