apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-gpu
spec:
  containers:
  - image: tensorflow/tensorflow:nightly-jupyter
    name: tensorflow-gpu
    ports:
    - containerPort: 8888
      protocol: TCP
  nodeSelector:
    gpu: "true"
