apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 namespace: default       
 name: app-access
rules:
- apiGroups: ["","apps"]
  resources: ["pods","deployments","services"]
  verbs:
  - create
  - get
  - list
  - update
  - delete   
