apiVersion: v1
kind: Pod
metadata:
  name: empty-pod
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - image: nginx:1.14
    name: volume-pod
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
