apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  volumes:
  - name: html
    nfs: 
      server: 10.100.0.101
      path: /nfsdir
  containers:
  - image: nginx:1.14
    name: volume-pod
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
