apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  volumes: 
  - name: html
    hostPath:
      path: /webdata
  containers:
  - image: nginx:1.14
    name: volume-pod
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
