apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: html
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: pvc-web
